#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [[ "$(uname)" == "Darwin" ]]; then
  (
    echo "--> Configuring macos defaults..."
    cd "${BASEDIR}"
    ./defaults.macos/defaults_user.sh
    ./defaults.macos/defaults_sudo.sh
    ./defaults.macos/configure_dock.sh

    echo "--> Configuring python for neovim..."
    cd "$HOME"
    for py in 2 3; do
      virtualenv -p "$(asdf which python"$py")" neovim"$py"
      source neovim"$py"/bin/activate
      python -m pip install pynvim neovim python-language-server jedi yamllint vim-vint ranger-fm
      deactivate
    done
  )
fi
