#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Parse flags
RUN_DEFAULTS=false
for arg in "$@"; do
  case $arg in
    --defaults)
      RUN_DEFAULTS=true
      shift
      ;;
  esac
done

cd "${BASEDIR}"
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [[ "$(uname)" == "Darwin" && "$RUN_DEFAULTS" == "true" ]]; then
  (
    echo "--> Configuring macos defaults..."
    cd "${BASEDIR}"
    ./defaults.macos/defaults_user.sh
    ./defaults.macos/defaults_sudo.sh
    ./defaults.macos/configure_dock.sh
  )
fi
