if [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc"
fi

# login-specific config (source_dir defined in bashrc)
source_dir "$HOME/.shellrc/login.d" sh
[[ "$(uname)" == "Darwin" ]] && source_dir "$HOME/.shellrc/login.d.osx" sh
